### ISSUE TITLE
Confirmation prompt

### ISSUE THREAD

**Issue by copystring** [Sebclem/OctoPrint-SimpleEmergencyStop#1]
Works well. I like this plugin. Especially since it is in the top bar.
However it needs a prompt to confirm the stop to avoid pressing it by accident.

**Comment by Sebclem** [comment]
Yes it's a good idea, i'm doing that as soon as possible !

**Comment by copystring** [comment]
Glad to hear that. Probably best to make that optional :) Maybe somebody wants the instant turn off?

**Comment by Sebclem** [comment]
Finish ! If you have any others suggestion, do not hesitate ! and thx :)

**Comment by ghost** [comment]
I am uninstalling this plugin because the whole purpose of an emergency stop is to immediately stop the machine. I have had to use this button twice and both times the additional click needed to stop the machine has caused me to crash. A better solution would be to have this button displayed somewhere on the screen where you are very unlikely to hit it by accident. Just as is done on CNC machines. Having the confirmation dialog negates the purpose of an emergency stop.

EDIT: Just noticed the confirmation can be shut off. Sorry for the intrusion. Carry on.

**Comment by tonsofpcs** [comment]
I just noticed this now as well.  After the E-stop failed to function when pressed.  Default should be instant-kill -- if there is a confirmation dialog (and I don't think there should be) it should be an option that you have to knowingly enable.

**Comment by ghost** [comment]
Yeah, it's actually worse than not having the plugin with the dialog in there. Because not only does it not stop the machine in an emergency it takes even longer to stop it when you aren't expecting to see a dialog. I guess reading everything thoroughly though would probably mention something about the dialog. But I never read the directions. Default to off though would be better. Better that someone accidently stops a print rather than crashes into one.

**Comment by Sebclem** [comment]
Yes you have absolutely right, I'll change it immediatel.
