### ISSUE TITLE
Emergency Stop button position in the top bar

### ISSUE THREAD

**Issue by ARU64** [Sebclem/OctoPrint-SimpleEmergencyStop#18]
With Octoprint 1.5.2, Python 3.7.3 and Octopi 0.18 the big estop or the small estop appear to low in the top bar.
![image](https://user-images.githubusercontent.com/49149180/102898490-dcb47180-4469-11eb-9b39-bcb4f9cafcc8.png)

**Comment by ZeekWorld** [comment]
Same with Dashboard plugin and UI Customizer
![image](https://user-images.githubusercontent.com/16088952/103468662-bc619e00-4d18-11eb-9267-7eb0f2fc7a2a.png)

**Comment by Sebclem** [comment]
Ok i can confirm that a conflict with UI Customizer, I will take a look at this and maybee open an issue on UI Customizer repo

**Comment by ZeekWorld** [comment]
Thank you.

**Comment by LazeMSS** [comment]
I think in general normally items to the top menu item is placed inside a single div to contain the element.

But im guessing the real problem is including a modal inside the header. If you want a confirm dialog then it should be placed at the end of the body/html.


A couple of other notes:
https://github.com/Sebclem/OctoPrint-SimpleEmergencyStop/tree/master/octoprint_simpleemergencystop/templates - you have "fontawesome.min.css" in her - this is wrong. its also includede here https://github.com/Sebclem/OctoPrint-SimpleEmergencyStop/tree/master/octoprint_simpleemergencystop/static/css which is the right place

Having inline style is bad practive when you have a css file:
https://github.com/Sebclem/OctoPrint-SimpleEmergencyStop/blob/master/octoprint_simpleemergencystop/templates/simpleemergencystop_navbar.jinja2#L2

**Comment by LazeMSS** [comment]
But i found something that I can try that might actually be better for both our plugins :)

**Comment by Sebclem** [comment]
The remaining issue should be fixed with the last release.

Sorry for late fix, i was quite busy lately

**Comment by Sebclem** [comment]
I'm closing this issue, feel free to re-open this issue or open a new one if you still have compatibility issue with UI Customizer
